//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW_Beta_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int idRecord { get; set; }
        public string idCarrito { get; set; }
        public Nullable<int> codigo { get; set; }
        public int contador { get; set; }
        public System.DateTime fechaCreado { get; set; }
    
        public virtual Videojuego Videojuego { get; set; }
    }
}
