//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW_Beta_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videojuego()
        {
            this.Carrito = new HashSet<Carrito>();
            this.DetalleOrden = new HashSet<DetalleOrden>();
        }
    
        public int codigo { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idDesarrolladora { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idPlataforma { get; set; }
        public decimal precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Desarrolladora Desarrolladora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Plataforma Plataforma { get; set; }
    }
}
